### ISSUE TITLE
Cannot read property 'lowerCasePath' of undefined

### ISSUE THREAD

**Issue by aricwalker** [aricwalker/project-icons#1]
Received this when opening a project that has not been opened before. 

```
Cannot read property 'lowerCasePath' of undefined
Hide Stack Trace
TypeError: Cannot read property 'lowerCasePath' of undefined
    at Object.activate (/Users/aricwalker/repositories/project-icons/lib/project-icons.js:14:55)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

**Comment by aricwalker** [comment]
Closing for now, this should be fixed with commit https://github.com/aricwalker/project-icons/commit/030f6ec9bafea85969b1fd98cf79a829adfe5478.
